"""changes fk ondelete cascade

Revision ID: 53d1dd49252f
Revises: b38ce0c50a23
Create Date: 2026-07-19 17:30:09.779810
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d1dd49252f'
down_revision: str | None = 'b38ce0c50a23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('changes_from_snapshot_fkey', 'changes', type_='foreignkey')
    op.drop_constraint('changes_to_snapshot_fkey', 'changes', type_='foreignkey')
    op.create_foreign_key('changes_from_snapshot_fkey', 'changes', 'snapshots',
                          ['from_snapshot'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('changes_to_snapshot_fkey', 'changes', 'snapshots',
                          ['to_snapshot'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('changes_from_snapshot_fkey', 'changes', type_='foreignkey')
    op.drop_constraint('changes_to_snapshot_fkey', 'changes', type_='foreignkey')
    op.create_foreign_key('changes_to_snapshot_fkey', 'changes', 'snapshots', ['to_snapshot'], ['id'])
    op.create_foreign_key('changes_from_snapshot_fkey', 'changes', 'snapshots', ['from_snapshot'], ['id'])
    # ### end Alembic commands ###
