"""add quote_cache

Revision ID: 600770bcc62f
Revises: 53d1dd49252f
Create Date: 2026-07-19 17:47:21.941709
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600770bcc62f'
down_revision: str | None = '53d1dd49252f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_cache',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('fmp_symbol', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('day_change_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_cache')
    # ### end Alembic commands ###
