"""add pillars table and security pillar fks

Revision ID: 9d433f552a62
Revises: 600770bcc62f
Create Date: 2026-07-19 17:56:22.331956
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d433f552a62'
down_revision: str | None = '600770bcc62f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pillars',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('primary_etf', sa.Text(), nullable=True),
    sa.Column('alt_etf', sa.Text(), nullable=True),
    sa.Column('caveat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('securities', sa.Column('pillar_id', sa.Text(), nullable=True))
    op.add_column('securities', sa.Column('crossref_pillar_id', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'securities', 'pillars', ['pillar_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'securities', 'pillars', ['crossref_pillar_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'securities', type_='foreignkey')
    op.drop_constraint(None, 'securities', type_='foreignkey')
    op.drop_column('securities', 'crossref_pillar_id')
    op.drop_column('securities', 'pillar_id')
    op.drop_table('pillars')
    # ### end Alembic commands ###
