"""add upload_staging

Revision ID: b38ce0c50a23
Revises: b9480c59bfc8
Create Date: 2026-07-19 17:01:28.272149
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b38ce0c50a23'
down_revision: str | None = 'b9480c59bfc8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_staging',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_format', sa.Text(), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_staging')
    # ### end Alembic commands ###
