"""initial schema

Revision ID: b9480c59bfc8
Revises: 
Create Date: 2026-07-19 16:40:29.048713
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9480c59bfc8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('fiscal_ending', sa.Date(), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=True),
    sa.Column('eps_actual', sa.Numeric(), nullable=True),
    sa.Column('eps_estimate', sa.Numeric(), nullable=True),
    sa.Column('surprise_pct', sa.Numeric(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'fiscal_ending', name='uq_earnings_ticker_fiscal')
    )
    op.create_table('estimates_snapshot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Text(), nullable=False),
    sa.Column('revenue_avg', sa.Numeric(), nullable=True),
    sa.Column('revenue_low', sa.Numeric(), nullable=True),
    sa.Column('revenue_high', sa.Numeric(), nullable=True),
    sa.Column('ebitda_avg', sa.Numeric(), nullable=True),
    sa.Column('net_income_avg', sa.Numeric(), nullable=True),
    sa.Column('eps_avg', sa.Numeric(), nullable=True),
    sa.Column('eps_low', sa.Numeric(), nullable=True),
    sa.Column('eps_high', sa.Numeric(), nullable=True),
    sa.Column('num_analysts_rev', sa.Integer(), nullable=True),
    sa.Column('num_analysts_eps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of', 'period_end', 'period_type', name='uq_estimates_period')
    )
    op.create_table('fundamentals_snapshot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('pe_trailing', sa.Numeric(), nullable=True),
    sa.Column('pe_forward', sa.Numeric(), nullable=True),
    sa.Column('peg', sa.Numeric(), nullable=True),
    sa.Column('price_to_sales', sa.Numeric(), nullable=True),
    sa.Column('price_to_book', sa.Numeric(), nullable=True),
    sa.Column('ev_to_revenue', sa.Numeric(), nullable=True),
    sa.Column('ev_to_ebitda', sa.Numeric(), nullable=True),
    sa.Column('profit_margin', sa.Numeric(), nullable=True),
    sa.Column('operating_margin', sa.Numeric(), nullable=True),
    sa.Column('roa', sa.Numeric(), nullable=True),
    sa.Column('roe', sa.Numeric(), nullable=True),
    sa.Column('revenue_ttm', sa.Numeric(), nullable=True),
    sa.Column('gross_profit_ttm', sa.Numeric(), nullable=True),
    sa.Column('eps_ttm', sa.Numeric(), nullable=True),
    sa.Column('rev_growth_yoy', sa.Numeric(), nullable=True),
    sa.Column('earnings_growth_yoy', sa.Numeric(), nullable=True),
    sa.Column('beta', sa.Numeric(), nullable=True),
    sa.Column('week52_high', sa.Numeric(), nullable=True),
    sa.Column('week52_low', sa.Numeric(), nullable=True),
    sa.Column('dma_50', sa.Numeric(), nullable=True),
    sa.Column('dma_200', sa.Numeric(), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(), nullable=True),
    sa.Column('shares_float', sa.Numeric(), nullable=True),
    sa.Column('pct_insiders', sa.Numeric(), nullable=True),
    sa.Column('pct_institutions', sa.Numeric(), nullable=True),
    sa.Column('target_high', sa.Numeric(), nullable=True),
    sa.Column('target_low', sa.Numeric(), nullable=True),
    sa.Column('target_consensus', sa.Numeric(), nullable=True),
    sa.Column('target_median', sa.Numeric(), nullable=True),
    sa.Column('target_av', sa.Numeric(), nullable=True),
    sa.Column('grades_strong_buy', sa.Integer(), nullable=True),
    sa.Column('grades_buy', sa.Integer(), nullable=True),
    sa.Column('grades_hold', sa.Integer(), nullable=True),
    sa.Column('grades_sell', sa.Integer(), nullable=True),
    sa.Column('grades_strong_sell', sa.Integer(), nullable=True),
    sa.Column('grades_consensus', sa.Text(), nullable=True),
    sa.Column('latest_quarter', sa.Date(), nullable=True),
    sa.Column('raw_av_overview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_fmp_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_fmp_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of', name='uq_fundamentals_ticker_asof')
    )
    op.create_table('nav_points',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('nav_per_share', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_nav', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_of')
    )
    op.create_table('news_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('sentiment_label', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'url', name='uq_news_ticker_url')
    )
    op.create_table('securities',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.Column('pillar', sa.Text(), nullable=True),
    sa.Column('isin', sa.Text(), nullable=True),
    sa.Column('thesis_note', sa.Text(), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_of')
    )
    op.create_table('changes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_snapshot', sa.BigInteger(), nullable=True),
    sa.Column('to_snapshot', sa.BigInteger(), nullable=True),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('units_before', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('units_after', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('units_delta', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('pct_delta', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_before', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cost_after', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('implied_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_snapshot'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['to_snapshot'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_snapshot', 'to_snapshot', 'ticker', name='uq_change_pair_ticker')
    )
    op.create_table('holdings_snapshot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('raw_ticker', sa.Text(), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'ticker', name='uq_holding_snapshot_ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings_snapshot')
    op.drop_table('changes')
    op.drop_table('snapshots')
    op.drop_table('securities')
    op.drop_table('news_item')
    op.drop_table('nav_points')
    op.drop_table('fundamentals_snapshot')
    op.drop_table('estimates_snapshot')
    op.drop_table('earnings_history')
    # ### end Alembic commands ###
